// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6CKK91xmKgHbt_zi3UIfY2EmNVnoySc',
    appId: '1:772040599519:web:cae240306041403cd7866a',
    messagingSenderId: '772040599519',
    projectId: 'todo-getx-f832a',
    authDomain: 'todo-getx-f832a.firebaseapp.com',
    storageBucket: 'todo-getx-f832a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_drah_Qn5p6lknJA3XFGY80Mam_Pm00k',
    appId: '1:772040599519:android:6decf29289a724b8d7866a',
    messagingSenderId: '772040599519',
    projectId: 'todo-getx-f832a',
    storageBucket: 'todo-getx-f832a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DNLCE8634rq5Wio5GEUTMUzHIiZ2mJQ',
    appId: '1:772040599519:ios:778f59f4b1b4f9c6d7866a',
    messagingSenderId: '772040599519',
    projectId: 'todo-getx-f832a',
    storageBucket: 'todo-getx-f832a.firebasestorage.app',
    iosBundleId: 'com.example.todoGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2DNLCE8634rq5Wio5GEUTMUzHIiZ2mJQ',
    appId: '1:772040599519:ios:778f59f4b1b4f9c6d7866a',
    messagingSenderId: '772040599519',
    projectId: 'todo-getx-f832a',
    storageBucket: 'todo-getx-f832a.firebasestorage.app',
    iosBundleId: 'com.example.todoGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs6CKK91xmKgHbt_zi3UIfY2EmNVnoySc',
    appId: '1:772040599519:web:6e5b0c814a8f3880d7866a',
    messagingSenderId: '772040599519',
    projectId: 'todo-getx-f832a',
    authDomain: 'todo-getx-f832a.firebaseapp.com',
    storageBucket: 'todo-getx-f832a.firebasestorage.app',
  );
}
